// <auto-generated />
using System;
using Faena.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Faena.Infrastructure.Migrations
{
    [DbContext(typeof(FaenaDbContext))]
    [Migration("20240827121026_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Faena.Domain.Flight.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalDateTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrivaldatetime");

                    b.Property<string>("ArrivalLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrivallocation");

                    b.Property<string>("DepartureDateTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departuredatetime");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departurelocation");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
